apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-hw-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mvkoshenkova-kuber-hw
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mvkoshenkova-kuber-hw
    spec:
      containers:
        - name: kuber-hw
          image: >-
            docker.io/mvkoshenkova/kuberhw:latest
          ports:
            - name: web
              containerPort: 8080
